name: Bending
description: Bending plugin for PaperMC.
author: Moros
version: ${pluginVersion}
main: me.moros.bending.Bending
softdepend: [WorldGuard, WorldEdit, GriefPrevention, Towny, RedProtect, PlaceholderAPI]
api-version: 1.16
commands:
  bending:
    description: Interact with the bending plugin
    default: true
    aliases: [bending,bend,b,avatar,atla,tla]
  preset:
    description: Manage bending presets
    default: true
    aliases: [presets,preset,pr,p]
  modify:
      description: Manage bending attribute modifiers
      default: op
      aliases: [bmodify,bmod,bm,modify,mod]
permissions:
  bending.admin:
    description: Grants access to all commands and abilities.
    default: op
    children:
      bending.player: true
      bending.fire.bluefire: true
      bending.command.reload: true
      bending.command.add: true
      bending.command.modify: true
  bending.player:
    default: true
    children:
      bending.command.bind: true
      bending.command.choose: true
      bending.command.display: true
      bending.command.help: true
      bending.command.preset: true
      bending.command.toggle: true
      bending.command.board: true
      bending.air: true
      bending.chi: true
      bending.earth: true
      bending.fire: true
      bending.water: true
  bending.air:
    children:
      bending.command.choose.Air: true
      bending.ability.AirAgility: true
      bending.ability.AirBlast: true
      bending.ability.AirBurst: true
      bending.ability.AirScooter: true
      bending.ability.AirShield: true
      bending.ability.AirSpout: true
      bending.ability.AirStream: true
      bending.ability.AirSuction: true
      bending.ability.AirSweep: true
      bending.ability.AirSwipe: true
      bending.ability.GracefulDescent: true
      bending.ability.Suffocate: true
      bending.ability.Tornado: true
      bending.ability.Twister: true
  bending.earth:
    children:
      bending.command.choose.Earth: true
      bending.ability.Catapult: true
      bending.ability.Collapse: true
      bending.ability.EarthArmor: true
      bending.ability.EarthBlast: true
      bending.ability.EarthGrab: true
      bending.ability.EarthSmash: true
      bending.ability.EarthTunnel: true
      bending.ability.RaiseEarth: true
      bending.ability.Shockwave: true
      bending.ability.DensityShift: true
  bending.fire:
    children:
      bending.command.choose.Fire: true
      bending.ability.Blaze: true
      bending.ability.Combustion: true
      bending.ability.FireBlast: true
      bending.ability.FireBlastCharged: true
      bending.ability.FireBurst: true
      bending.ability.FireJet: true
      bending.ability.FireShield: true
      bending.ability.HeatControl: true
      bending.ability.Lightning: true
      bending.ability.FireWall: true
      bending.ability.FireKick: true
      bending.ability.FireSpin: true
      bending.ability.FireWheel: true
      bending.ability.JetBlast: true
      bending.ability.JetBlaze: true
  bending.water:
    children:
      bending.command.choose.Water: true
      bending.ability.Bloodbending: true
      bending.ability.FastSwim: true
      bending.ability.HealingWaters: true
      bending.ability.Hydrosink: true
      bending.ability.IceBlast: true
      bending.ability.IceBullet: true
      bending.ability.IceSpike: true
      bending.ability.OctopusForm: true
      bending.ability.PhaseChange: true
      bending.ability.Surge: true
      bending.ability.Torrent: true
      bending.ability.WaterArms: true
      bending.ability.WaterArmsFreeze: true
      bending.ability.WaterArmsGrab: true
      bending.ability.WaterArmsGrapple: true
      bending.ability.WaterArmsPull: true
      bending.ability.WaterArmsPunch: true
      bending.ability.WaterArmsSpear: true
      bending.ability.WaterBubble: true
      bending.ability.WaterManipulation: true
      bending.ability.WaterSpout: true
